# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        files: ^(app/|tests/)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^dist/
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        files: ^(app/|tests/)
